### ISSUE TITLE
Trying to call an ApplePaySession API from an insecure document.

### ISSUE THREAD

**Issue by justcttseng** [datatrans/apple-pay-web-sample#1]
I tried and followed the step to build an apple pay web demo.

It works fine on macOS but something wrong on iPhone.

> `InvalidAccessError (DOM Exception 15): Trying to call an ApplePaySession API from an insecure document.
(anonymous function) — index.js:77
applePayButtonClicked — index.js:77
onclick — paypages.html:33
`

Which files should I rewrite?

**Comment by dmengelt** [comment]
hi @justcttseng sorry for the late reply. please make sure you serve your sample from HTTPS. The following link works for me on my test iPhone:

https://applepay-datatrans-sample.herokuapp.com/
