### ISSUE TITLE
abandon a transaction on cancel is not handled

### ISSUE THREAD

**Issue by Kiran-N** [datatrans/apple-pay-web-sample#2]
"_**This function can be called even after an onpaymentauthorized event has been dispatched. Both the user and the web page can dismiss the payment sheet and abandon the transaction.**_"

If user cancels the transaction after onpaymentauthorized, how to abandon the transaction, while the onpaymentauthorized triggers the backend and do authorization.

session.oncancel = (event) => {
        console.log("oncancel");
        console.log(event);
    };

**Comment by fgrDtrx** [comment]
HI @Kiran-N 

session.oncancel is usually only invoked *before* on onpaymentauthorized. So in this case there is no transaction that needs to be abandoned or canceled. I just checked and what can happen is that even if the user authorizes with TouchId and the progress bar says processing cancel can still be clicked and the event will be fired. But in any case if cancel is invoked first there is no need to cancel the transaction. So is your question about how to cancel a transaction which has been authorized already or is your question about the behaviour that a user can still click even though onpaymentauthorized has already been fired?

**Comment by Kiran-N** [comment]
My question is about how to handle transaction which has been authorized by processor but user has clicked on cancel.

Now the payment is already is system, user may think it is cancelled. but it is already in the system, it will go ahead and settle if nothing is done on cancel.

**Comment by fgrDtrx** [comment]
Unfortenatly the cancel callback is not triggred after the user confirmed. It will only be triggred before confirmation and shortly after while the process is still running. So in the second case you will have to cancel the transaction on request by the user. We advise to use reqtype == NOA which does not auto settle. Please refer to our cancel API here: https://docs.datatrans.ch/docs/payment-process-cancel. If the cancel callback is triggred no authorization will take place.

**Comment by dmengelt** [comment]
closing
